### ISSUE TITLE
Clases CSS

### ISSUE THREAD

**Issue by erxxc08** [CoderAnchel/My-first-DAPP#1]
Che boludo, alguien sabe como seleccionar un elemento de html en JS? Gracias <3

**Comment by CoderAnchel** [comment]
Tienes que utilizar un Query Selector, pon una variable para guardar el elemento:

`const nav = document.querySelector(".nav");`

**Comment by erxxc08** [comment]
> Owner

**Comment by erxxc08** [comment]
> Tienes que utilizar un Query Selector, pon una variable para guardar el elemento:
> 
> `const nav = document.querySelector(".nav");`

Gracias

**Comment by erxxc08** [comment]
Gracias boludo
